import { NextRequest, NextResponse } from 'next/server';
import { getLocalOrder } from '@/lib/mock-data';
import { getSupabaseAdmin, isSupabaseConfigured } from '@/lib/supabase';
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';

// Helper to ensure all strings passed to pdf-lib StandardFonts are 100% WinAnsi safe (0x20 - 0x7E)
function toWinAnsiSafe(text?: string, fallback: string = ''): string {
  if (!text) return fallback;
  const sanitized = text
    .split('')
    .map((char) => {
      const code = char.charCodeAt(0);
      return code >= 32 && code <= 126 ? char : '';
    })
    .join('')
    .replace(/\s+/g, ' ')
    .trim();

  return sanitized || fallback;
}

function getSafeBookTitle(rawTitle: string, bookId?: string): string {
  if (!rawTitle) rawTitle = '';
  if (rawTitle.includes('Media Player') || bookId === 'book-1') {
    return '90s Retro Media Player PRO - User & Developer Guide';
  }
  if (rawTitle.includes('Tarot') || bookId === 'book-2') {
    return 'Rider-Waite 3-Card Tarot Reading App - Guide & Manual';
  }
  if (rawTitle.includes('Task Manager') || bookId === 'book-3') {
    return 'SQLite Task Manager PRO (Futuristic Edition) - Guide & Manual';
  }
  const ascii = toWinAnsiSafe(rawTitle, '');
  return ascii || 'Vibe Coding E-book Digital Edition';
}

function getSafeChapterLines(rawTitle: string, bookId?: string): string[] {
  if (rawTitle.includes('Media Player') || bookId === 'book-1') {
    return [
      'Chapter 1: 90s Retro Audio Deck Architecture & Design Concepts',
      'Chapter 2: Portable Package Setup and Windows System Requirements',
      'Chapter 3: VFD Screen, Audio Sliders, and Transport Controls Guide',
      'Chapter 4: Playlist Rack Management and Real-time Playback Engine',
      'Chapter 5: Audio Engine Testing, Formats (.mp3, .wav, .flac), and Distribution',
      '',
      'Thank you for reading 90s Retro Media Player PRO Guide!',
      'This verified PDF was generated by Vibe Coding Platform.',
    ];
  }
  if (rawTitle.includes('Tarot') || bookId === 'book-2') {
    return [
      'Chapter 1: Rider-Waite Symbolism and Mystical Divination Archetypes',
      'Chapter 2: The 3-Card Reading Spread: Past, Present, and Future',
      'Chapter 3: Mystic Velvet Interface and BGM Ambient Audio Deck Setup',
      'Chapter 4: Shuffling Algorithm, Card Reveal, and Interpretation Rules',
      'Chapter 5: Prediction Logs, Sound Control, and Lifestyle UX Patterns',
      '',
      'Thank you for reading Rider-Waite Tarot App Guide!',
      'This verified PDF was generated by Vibe Coding Platform.',
    ];
  }
  return [
    'Chapter 1: SQLite Architecture and Admin Authentication Security',
    'Chapter 2: Futuristic Minimalist UI & Dark/Light Theme Customization',
    'Chapter 3: Dashboard Metrics, Task Analytics, and Productivity Cards',
    'Chapter 4: Full Task Management (CRUD, Priority Levels, Categories)',
    'Chapter 5: Soft-Delete Recycle Bin and CSV Export/Import Workflow',
    'Chapter 6: Automated SQLite Database Backup & Recovery Procedures',
    '',
    'Thank you for reading SQLite Task Manager PRO Guide!',
    'This verified PDF was generated by Vibe Coding Platform.',
  ];
}

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const orderId = searchParams.get('orderId');
  const forceDownload = searchParams.get('download') === '1';

  if (!orderId) {
    return new NextResponse('Invalid order request', { status: 400 });
  }

  let order: {
    id: string;
    customerName: string;
    customerEmail?: string;
    bookTitle: string;
    bookId?: string;
    bookPrice?: number;
    status: string;
  } | null = null;

  // 1. Check Supabase
  const supabaseAdmin = getSupabaseAdmin();
  if (isSupabaseConfigured() && supabaseAdmin) {
    try {
      const { data } = await supabaseAdmin
        .from('orders')
        .select('id, customer_name, customer_email, book_title, book_id, book_price, status')
        .eq('id', orderId)
        .single();
      if (data) {
        order = {
          id: data.id,
          customerName: data.customer_name,
          customerEmail: data.customer_email,
          bookTitle: data.book_title,
          bookId: data.book_id,
          bookPrice: data.book_price,
          status: data.status,
        };
      }
    } catch (e) {
      console.warn('Supabase fetch error in download:', e);
    }
  }

  // 2. Check local memory
  if (!order) {
    const local = getLocalOrder(orderId);
    if (local) {
      order = {
        id: local.id,
        customerName: local.customerName,
        customerEmail: local.customerEmail,
        bookTitle: local.bookTitle,
        bookId: local.bookId,
        bookPrice: local.bookPrice,
        status: local.status,
      };
    }
  }

  // 3. Stateless Token Fallback for Serverless / Cloud deployments (Vercel)
  const token = searchParams.get('token');
  if (!order && token) {
    try {
      const raw = Buffer.from(token, 'base64').toString('utf-8');
      if (raw.startsWith('{')) {
        const decoded = JSON.parse(raw);
        if (decoded && (decoded.id === orderId || decoded.status === 'PAID')) {
          order = {
            id: decoded.id || orderId,
            customerName: decoded.name || decoded.customerName || 'Verified Customer',
            customerEmail: decoded.email,
            bookTitle: decoded.title || decoded.bookTitle || 'Vibe Coding E-book',
            bookId: decoded.bookId || 'book-1',
            bookPrice: decoded.price || 199,
            status: 'PAID',
          };
        }
      }
    } catch (e) {
      console.warn('Token decode error in download:', e);
    }
  }

  // 4. Graceful fallback for demo orders (starts with ORD-)
  if (!order && orderId.startsWith('ORD-')) {
    order = {
      id: orderId,
      customerName: 'Verified Customer',
      bookTitle: 'Vibe Coding E-book Guide',
      bookId: 'book-1',
      status: 'PAID',
    };
  }

  if (!order || order.status !== 'PAID') {
    return new NextResponse('ขออภัย ลิงก์ดาวน์โหลดไม่ถูกต้อง หรือคำสั่งซื้อนี้ยังไม่ได้รับการชำระเงิน', {
      status: 403,
      headers: { 'Content-Type': 'text/plain; charset=utf-8' },
    });
  }

  try {
    // Generate a 100% valid, standard PDF using pdf-lib
    const pdfDoc = await PDFDocument.create();
    const timesRomanFont = await pdfDoc.embedFont(StandardFonts.TimesRoman);
    const timesBoldFont = await pdfDoc.embedFont(StandardFonts.TimesRomanBold);
    const courierFont = await pdfDoc.embedFont(StandardFonts.Courier);

    // Page 1: Cover & License
    const page = pdfDoc.addPage([595.28, 841.89]); // A4 size in points
    const { width, height } = page.getSize();

    // Top Header Banner
    page.drawRectangle({
      x: 0,
      y: height - 100,
      width: width,
      height: 100,
      color: rgb(0.12, 0.35, 0.85),
    });

    page.drawText('VIBE CODING E-BOOK READER', {
      x: 50,
      y: height - 55,
      size: 20,
      font: timesBoldFont,
      color: rgb(1, 1, 1),
    });

    page.drawText('Official Digital Edition - Verified Copy', {
      x: 50,
      y: height - 78,
      size: 11,
      font: timesRomanFont,
      color: rgb(0.85, 0.9, 1),
    });

    // Content Card
    page.drawRectangle({
      x: 45,
      y: height - 260,
      width: width - 90,
      height: 130,
      color: rgb(0.96, 0.97, 0.99),
      borderColor: rgb(0.85, 0.88, 0.92),
      borderWidth: 1,
    });

    page.drawText('Order Information & Verification', {
      x: 65,
      y: height - 160,
      size: 14,
      font: timesBoldFont,
      color: rgb(0.1, 0.15, 0.25),
    });

    const safeOrderId = toWinAnsiSafe(order.id, 'ORD-UNKNOWN');
    page.drawText(`Order ID: ${safeOrderId}`, {
      x: 65,
      y: height - 185,
      size: 12,
      font: courierFont,
      color: rgb(0.12, 0.35, 0.85),
    });

    const safeCustomer = toWinAnsiSafe(order.customerName, '') || 
      (order.customerEmail ? order.customerEmail.split('@')[0] : 'Verified Reader');

    page.drawText(`Licensed to: ${safeCustomer}`, {
      x: 65,
      y: height - 208,
      size: 11,
      font: timesRomanFont,
      color: rgb(0.2, 0.25, 0.3),
    });

    page.drawText('Payment Status: PAID (Full Digital Rights)', {
      x: 65,
      y: height - 230,
      size: 11,
      font: timesBoldFont,
      color: rgb(0.1, 0.6, 0.3),
    });

    // Book Title Section
    page.drawText('BOOK TITLE:', {
      x: 50,
      y: height - 310,
      size: 12,
      font: timesBoldFont,
      color: rgb(0.4, 0.45, 0.5),
    });

    const safeTitle = getSafeBookTitle(order.bookTitle, order.bookId);
    page.drawText(safeTitle, {
      x: 50,
      y: height - 335,
      size: 13,
      font: timesBoldFont,
      color: rgb(0.1, 0.1, 0.1),
    });

    // Chapter Preview / Sample content
    page.drawText('CHAPTER HIGHLIGHTS & CONTENT SUMMARY', {
      x: 50,
      y: height - 385,
      size: 12,
      font: timesBoldFont,
      color: rgb(0.2, 0.3, 0.5),
    });

    const lines = getSafeChapterLines(order.bookTitle, order.bookId);

    let currentY = height - 415;
    for (const line of lines) {
      const safeLine = toWinAnsiSafe(line, '');
      if (safeLine) {
        page.drawText(safeLine, {
          x: 50,
          y: currentY,
          size: 10,
          font: timesRomanFont,
          color: rgb(0.25, 0.25, 0.3),
        });
      }
      currentY -= 20;
    }

    // Footer
    page.drawText('Generated by Vibe Coding E-book Shop Platform - MIT App Inventor & Mobile Ready', {
      x: 50,
      y: 40,
      size: 9,
      font: timesRomanFont,
      color: rgb(0.6, 0.65, 0.7),
    });

    const pdfBytes = await pdfDoc.save();

    const disposition = forceDownload ? 'attachment' : 'inline';

    return new NextResponse(Buffer.from(pdfBytes), {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `${disposition}; filename="Ebook-${safeOrderId}.pdf"`,
        'Cache-Control': 'no-cache',
      },
    });
  } catch (err: any) {
    console.error('PDF generation error:', err);
    return new NextResponse('Error generating PDF file: ' + err.message, { status: 500 });
  }
}
